### ISSUE TITLE
This error happens in the tests, at well, random

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1221] opened 2017-08-02 10:32 UTC
======================================================================

```
ERROR: test_datetime_generator_on_leap_day (opal.tests.test_command_create_random_data.DateTimeGeneratorTestCase)
```
----------------------------------------------------------------------
```
Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched

    return func(*args, **keywargs)

  File "/home/travis/build/openhealthcare/opal/opal/tests/test_command_create_random_data.py", line 63, in test_datetime_generator_on_leap_day

    self.assertIsInstance(crd.date_time_generator(), datetime.datetime)

  File "/home/travis/build/openhealthcare/opal/opal/management/commands/create_random_data.py", line 112, in date_time_generator

    d = date_generator(*args, **kwargs)

  File "/home/travis/build/openhealthcare/opal/opal/management/commands/create_random_data.py", line 107, in date_generator

    day = random.randint(first_day, last_day)

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/random.py", line 227, in randint

    return self.randrange(a, b+1)

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/random.py", line 205, in randrange

    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))

ValueError: empty range for randrange() (29,29, 0)
```

**Comment by davidmiller** [comment] 2017-08-07 09:46
@fredkingham is this a duplicate of #955 ?

**Comment by davidmiller** [comment] 2018-10-26 08:34
This gets raised when the call to `randint` is `randint(29, 28)` (Which shouldn't happen.)

Re-running this test now, the values going in to randint are `(1, 28)` every time e.g. not random, therefore closing this as resolved.

If it comes up again, let's fix it quickly rather than waiting ages though!

**Closed by davidmiller** 2018-10-26 08:34 UTC
Labels: Backlog, unplanned
